name: GitHub Action triggers Azure
on:
  push:
    branches: [main]

jobs:
  trigger-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure Pipeline
        run: |
          az pipelines run \
            --name "AGAPrjCICT-Pipeline" \
            --project "AGA Assurance Collective Prj 1" \
            --org "https://dev.azure.com/<org>"
